"use client";

import { useState } from "react";
import Head from "next/head";

import NewTweet from "@/components/NewTweet";
import Tweet from "@/components/Tweet";

export default function Timeline() {
  const [message, setMessage] = useState("");

  const backgroundImageStyle = {
    backgroundImage: "url(/cryp-twitter.jpg)",
    backgroundSize: "cover",
    backgroundPosition: "center",
    height: "100vh",
    width: "100vw",
    color: "white",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
  };

  return (
    <div
      style={backgroundImageStyle}
      className="container d-block background-color='#0f1221' align-items-center justify-content-center mx-lg-auto"
    >
      <Head>
        <title>CrypTwitter | Timeline</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="row flex-lg-row-reverse align-items-center g-5 py-5">
        <div className="col-2">&nbsp;</div>
        <div className="col-8 mt-5">
          <h1 className="display-5 fw-bold lh-1 mb-3 text-body-emphasis">
            CrypTwitter
          </h1>
          <div className="d-flex justify-content-start mt-5">
            <NewTweet />
            <Tweet />
          </div>

          {message ? (
            <div className="alert alert-success mt-5 opacity-75">{message}</div>
          ) : null}
        </div>
        <div className="position-fixed bottom-0 start-50 translate-middle  px-9 mt-9 w-full text-center">
          Photo by{" "}
          <a href="https://unsplash.com/pt-br/@iamchang?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">
            Chang Duong
          </a>{" "}
          in{" "}
          <a href="https://unsplash.com/pt-br/fotografias/foto-da-silhueta-de-seis-pessoas-no-topo-da-montanha-Sj0iMtq_Z4w?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">
            Unsplash
          </a>
        </div>
        <div className="col-2">&nbsp;</div>
      </div>
    </div>
  );
}
